-- New project schema. Public toilet records are publicly readable; writes require an owner/admin.
create table if not exists public.toilets (
 id text primary key,
 name text not null,
 lat double precision not null check (lat between -90 and 90),
 lng double precision not null check (lng between -180 and 180),
 address text not null default '',
 hours text not null default '',
 type text not null default '',
 retrieved_at date not null
);
alter table public.toilets enable row level security;
revoke all on public.toilets from anon, authenticated;
grant select on public.toilets to anon, authenticated;
drop policy if exists "Public toilet read access" on public.toilets;
create policy "Public toilet read access" on public.toilets for select to anon, authenticated using (true);

-- Public profiles contain only the display name used beside a review.
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 nickname text not null check (char_length(nickname) between 1 and 40),
 created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
grant select on public.profiles to anon, authenticated;
grant update on public.profiles to authenticated;
drop policy if exists "Public profile read access" on public.profiles;
create policy "Public profile read access" on public.profiles for select to anon, authenticated using (true);
drop policy if exists "Users update their profile" on public.profiles;
create policy "Users update their profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
 insert into public.profiles (id,nickname)
 values (new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),nullif(new.raw_user_meta_data->>'name',''),split_part(coalesce(new.email,'회원'),'@',1)))
 on conflict (id) do nothing;
 return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
insert into public.profiles (id,nickname)
select id,coalesce(nullif(raw_user_meta_data->>'full_name',''),nullif(raw_user_meta_data->>'name',''),split_part(coalesce(email,'회원'),'@',1)) from auth.users
on conflict (id) do nothing;

create table if not exists public.reviews (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 toilet_id text not null references public.toilets(id) on delete cascade,
 toilet_name text not null check (char_length(toilet_name) between 1 and 120),
 title text not null check (char_length(title) between 1 and 80),
 content text not null check (char_length(content) between 1 and 1000),
 rating smallint not null check (rating between 1 and 5),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists reviews_created_at_idx on public.reviews (created_at desc);
create index if not exists reviews_toilet_id_idx on public.reviews (toilet_id);
alter table public.reviews enable row level security;
grant select on public.reviews to anon, authenticated;
grant insert,update,delete on public.reviews to authenticated;
grant usage,select on sequence public.reviews_id_seq to authenticated;
drop policy if exists "Public review read access" on public.reviews;
create policy "Public review read access" on public.reviews for select to anon, authenticated using (true);
drop policy if exists "Members create reviews" on public.reviews;
create policy "Members create reviews" on public.reviews for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Authors update reviews" on public.reviews;
create policy "Authors update reviews" on public.reviews for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Authors delete reviews" on public.reviews;
create policy "Authors delete reviews" on public.reviews for delete to authenticated using ((select auth.uid()) = user_id);
