import {ranked,routeUrl} from './geo.mjs';
const $=id=>document.getElementById(id), cityHall={lat:37.5663,lng:126.9779};
let rows=[],origin=null,sorted=[],selected=null,map,markers,originMarker,accuracyCircle,manual=false,busy=false;
const status=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error);};
const fmt=d=>d<1000?`${Math.round(d)}m`:`${(d/1000).toFixed(1)}km`;
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;}
function icon(active){return L.divIcon({className:`wc-marker${active?' active':''}`,html:'WC',iconSize:[32,30],iconAnchor:[16,15]});}
function drawMarkers(){if(!map)return;markers.clearLayers();const bounds=map.getBounds().pad(.1);const visible=rows.filter(t=>bounds.contains([t.lat,t.lng]));for(const t of visible){const marker=L.marker([t.lat,t.lng],{icon:icon(t.id===selected),title:t.name}).addTo(markers);marker.on('click',()=>select(t.id,true));}}
function select(id,fromMap=false){selected=id;renderList();const t=rows.find(t=>t.id===id);if(map&&t){if(!fromMap)map.setView([t.lat,t.lng],17);drawMarkers();const box=el('div');box.append(el('strong','',t.name),el('div','',t.hours||'개방시간 정보 없음'));L.popup().setLatLng([t.lat,t.lng]).setContent(box).openOn(map);}}
function renderList(){const container=$('list');container.replaceChildren();let shown=sorted.slice(0,6);if(selected&&!shown.some(t=>t.id===selected)){const t=sorted.find(t=>t.id===selected);if(t)shown=[t,...shown.slice(0,5)];}for(const t of shown){const card=el('article',`card${t.id===selected?' selected':''}`),top=el('div','card-top');top.append(el('span','badge',t.type||'유형 미제공'),el('span','distance',fmt(t.distance)));const title=el('button','card-select',t.name);title.onclick=()=>select(t.id);const route=el('button','route','이 화장실로 도보 길찾기 ↗');route.onclick=()=>navigate(t);card.append(top,title,el('p','',t.address||'주소 정보 없음'),el('p','hours',t.hours||'개방시간 정보 없음'),route);container.append(card);}}
function refresh(){sorted=ranked(rows,origin||cityHall);selected=sorted[0]?.id;$('count').textContent=`전체 ${rows.length.toLocaleString()}곳`;$('list-title').textContent=origin?'출발지에서 가까운 화장실':'서울시청 주변';$('distance-note').textContent=origin?'직선거리 순 · 실제 도보 경로는 카카오맵에서 확인':'미리보기 · 서울시청 기준 직선거리';renderList();drawMarkers();}
function setOrigin(point,label,accuracy=0){origin=point;manual=false;$('manual').textContent='지도에서 출발지 선택';$('map-label').textContent=label;if(map){if(originMarker)map.removeLayer(originMarker);if(accuracyCircle)map.removeLayer(accuracyCircle);originMarker=L.circleMarker([point.lat,point.lng],{radius:8,color:'#fff',weight:3,fillColor:'#14a8a1',fillOpacity:1}).addTo(map);if(accuracy)accuracyCircle=L.circle([point.lat,point.lng],{radius:accuracy,color:'#14a8a1',weight:1,fillOpacity:.07}).addTo(map);map.setView([point.lat,point.lng],16);}refresh();status(sorted[0]?.distance>10000?'현재 출발지 주변은 서울 데이터의 서비스 범위 밖입니다. 서울 내 출발지를 선택해 주세요.':`${label}${accuracy?` · 위치 오차 약 ${Math.round(accuracy)}m`:''}. 가까운 화장실을 찾았습니다.`,sorted[0]?.distance>10000);}
function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject({code:0});navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0});});}
async function locate(andRoute=false,target=null){if(busy)return;busy=true;$('nearest').disabled=true;$('locate').disabled=true;status('현재 위치를 확인하고 있습니다. 위치 권한을 허용해 주세요.');try{const p=await getPosition();setOrigin({lat:p.coords.latitude,lng:p.coords.longitude},'내 현재 위치',p.coords.accuracy);if(andRoute){if(p.coords.accuracy>500){status('위치 오차가 커서 바로 안내하지 않았어요. 지도에서 출발지를 선택하거나 위치를 다시 확인해 주세요.',true);}else navigate(target||sorted[0]);}}catch(e){const messages={1:'위치 권한이 차단되어 있습니다. 브라우저에서 위치를 허용하거나 지도에서 출발지를 선택해 주세요.',2:'현재 위치를 확인할 수 없습니다. 지도에서 출발지를 선택해 주세요.',3:'위치 확인 시간이 초과되었습니다. 다시 시도하거나 지도에서 출발지를 선택해 주세요.'};status(messages[e.code]||'이 브라우저에서 위치를 사용할 수 없습니다. 지도에서 출발지를 선택해 주세요.',true);}finally{busy=false;$('nearest').disabled=!rows.length;$('locate').disabled=false;}}
function navigate(t){if(!t)return;if(!origin){locate(true,t);return;}if(sorted[0]?.distance>10000){status('주변에 수록된 화장실이 없습니다. 서울 지역을 대상으로 이용해 주세요.',true);return;}window.location.assign(routeUrl(origin,t));}
$('nearest').onclick=()=>{if(origin)navigate(sorted[0]);else locate(true);};$('locate').onclick=()=>locate();$('manual').onclick=()=>{if(!map){status('지도를 사용할 수 없습니다. 새로고침한 뒤 다시 시도해 주세요.',true);return;}manual=!manual;$('manual').textContent=manual?'출발지 선택 취소':'지도에서 출발지 선택';status(manual?'지도에서 출발할 위치를 눌러 주세요.':'출발지 선택을 취소했습니다.');if(manual&&innerWidth<761)$('map').scrollIntoView({behavior:'smooth',block:'center'});};
try{if(!window.L)throw Error('지도 로딩 실패');map=L.map('map',{zoomControl:false}).setView([cityHall.lat,cityHall.lng],16);L.control.zoom({position:'topright'}).addTo(map);let tileErrors=0;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>{if(++tileErrors>=3)$('map-error').hidden=false;}).on('tileload',()=>{$('map-error').hidden=true;tileErrors=0;}).addTo(map);markers=L.layerGroup().addTo(map);map.on('moveend',drawMarkers);map.on('click',e=>{if(manual&&!busy)setOrigin({lat:e.latlng.lat,lng:e.latlng.lng},'지도에서 선택한 출발지');});}catch{$('map-error').hidden=false;}
async function load(){try{const response=await fetch('./toilets.json');if(!response.ok)throw Error('데이터 오류');const data=await response.json();rows=data.rows.filter(t=>Number.isFinite(t.lat)&&Number.isFinite(t.lng));if(!rows.length)throw Error('데이터 없음');$('data-info').textContent=`수집일 ${data.retrievedAt} · 위치가 유효한 ${rows.length.toLocaleString()}곳. 내려받은 공공데이터를 사용하며 자동 갱신하지 않습니다.`;refresh();status('현재 위치를 허용하면 가장 가까운 화장실의 길찾기를 시작합니다.');$('nearest').disabled=false;}catch{status('화장실 정보를 불러오지 못했습니다. 연결을 확인하고 다시 시도해 주세요.',true);const retry=el('button','route','데이터 다시 불러오기');retry.onclick=load;$('list').replaceChildren(retry);}}load();
